# Generated by Django 5.1.1 on 2024-09-16 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_soldier_delete_solider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Soldier',
            new_name='SoldierModel',
        ),
    ]
