# Generated by Django 5.1.1 on 2024-09-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_rename_soldier_soldiermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='bioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=100)),
                ('lastname', models.TextField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('company', models.TextField(max_length=100)),
                ('favouritecar', models.TextField(max_length=100)),
                ('notes', models.TextField(max_length=100)),
            ],
        ),
    ]
