# Generated by Django 5.1.1 on 2024-09-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_biomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='biomodel',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='biomodel',
            name='favouritecar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='biomodel',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='biomodel',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='biomodel',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='biomodel',
            name='notes',
            field=models.CharField(max_length=100),
        ),
    ]
